import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Footer from "../componentes/About/Footer";
import About from "./about";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Potfolio CB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {/* <p>
            Carolina Magali Barragàn &nbsp;
            <code className={styles.code}>|| Dev 💻</code>
          </p> */}

          <div>
            <a
              href="https://certificates.soyhenry.com/cert?id=b8a0a083-5052-4128-b832-6fdb4dfc8201"
              target="_blank"
              rel="noopener noreferrer"
            >
              Full Stack Web Developer{" "}
              <Image
                src="/codigo.png"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={84}
                priority
              />
            </a>
          </div>
        </div>
        <div className={styles.fondo}>
          <div className={styles.titulo} width={180} height={280}>
            {" "}
            Carolina Barragàn
          </div>
        </div>
        <br />
        <div>
          <About />
        </div>
        <br />

        <div>
          <a
            href="https://github.com/carobarragan/Proyecto-individua.git"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Proyecto Individual<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Dogs Es una aplicación de adopcion de perros.Hecho Redux, Express,
              PostgreSQL, Sequelize,entre otros.&nbsp;
            </p>
            <div>
              <Image src="/pi.jpeg" width={240} height={171} priority />
            </div>
          </a>

          <a
            href="https://wetravel-app.vercel.app/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Proyecto Grupal <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Es una aplicación de viaje, donde cuenta con tres perfiles;
              Administrador, este tiene el control total de la aplicacion a
              travès de un panel. Anfitrión, pone a disposicion el servicio;
              Huesped, dispone de la adquisiciòn del servicio y ademas puede
              postear imagenes en tiempo reales para que las demas personas
              puedan ver imagenes del hotel tomadas por clientes. Wetravel es un
              app para brindarles comodidades a todos..
            </p>
            <div>
              <Image src="/pg.jpeg" width={240} height={171} priority />
            </div>
          </a>

          <a
            href="https://certificates.soyhenry.com/cert?id=b8a0a083-5052-4128-b832-6fdb4dfc8201"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Mis Hablidades <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              .JavaScript, Redux, React, Next.js, Node, SQL, PostgreSQL, Github,
              HTML5, styledComponets
            </p>
            {/* <div>
              <Image href="html-5--v.png" width={24} height={24} />
              <p>HTML.</p>
            </div> */}
          </a>
        </div>
      </main>
      <div className={styles.foter}>
        <Footer />
      </div>
    </>
  );
}
