import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Footer from "../componentes/About/Footer";
import About from "./about";
import Skill from "./Skill";
import GithubIcon from "../componentes/About/Github";
import LinkedInIcon from "../componentes/Linkedln";
import Proyecto from "./Proyectos";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Potfolio CB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.fondo}>
          <div className={styles.titulo} width={180} height={280}>
            {" "}
            Carolina Barragán
          </div>
          {/* <div className={styles.subtitulo}>
            <p>
              Una desarrolladora Full Stack muy apasionada y motivada con agiles
              Metodologias. Siempre lista para aplicar lo que sé y aprender
              sobre lo que no sé 💻.
            </p>
          </div> */}
          <br />
          <br />
          <div className={styles.icons}>
            <a
              href="https://github.com/carobarragan"
              target="_blank"
              rel="noreferrer"
            >
              <GithubIcon />
            </a>
            <a
              rel="noopener noreferrer"
              target="_blank"
              href="https://www.linkedin.com/in/caro-barragan/"
            >
              <LinkedInIcon />
            </a>
          </div>
        </div>

        <br />
        <div className={styles.About}>
          <About />
        </div>
        <br />
        <br />
        <div>
          <Proyecto />
        </div>

        <div className={styles}>
          <Skill></Skill>
        </div>
      </main>
      <div className={styles.foter}>
        <Footer />
      </div>
    </>
  );
}
